/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.btljava.ui;

import com.btljava.helper.MessageDialog;
import com.btljava.helper.ShereData;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class fromMainss extends javax.swing.JFrame {
//    private doiituongss doituongss;
//    private loaisanphamss lsp;
//    private taikhoanss tk;
//    private nhommauss nm;
//    private chucvuss cv;
//    private nhanvienss nv;
//    private benhnhanss bv;
//    private tienluongss tl;
//    private sanphamss sp;
//    private hoadonss hd;
//    private khoss kh;
//    private loaigiuongss lg;
//    private giuongnguss gn;
//    private cuochenss ch;
//    private nhataitross ntt;
//    private hoadonnhapss hdn;
//    private guiemails email;
//    private thongke thongkes;
    /**
     * Creates new form fromMainss
     */
    public fromMainss() {
        initComponents();
        
        jButton38.setBackground(Color.orange);
        jButton21.setBackground(Color.orange);
        jButton22.setBackground(Color.orange);
        jButton23.setBackground(Color.orange);
        jButton24.setBackground(Color.orange);
        jButton25.setBackground(Color.orange);
        jButton26.setBackground(Color.orange);
        jButton27.setBackground(Color.orange);
        jButton28.setBackground(Color.orange);
        jButton29.setBackground(Color.orange);
        jButton30.setBackground(Color.orange);
        jButton31.setBackground(Color.orange);
        jButton32.setBackground(Color.orange);
        jButton33.setBackground(Color.orange);
        jButton34.setBackground(Color.orange);
        jButton35.setBackground(Color.orange);
        jButton36.setBackground(Color.orange);
        jButton37.setBackground(Color.orange);
        jButton38.setBackground(Color.orange);
        jButton39.setBackground(Color.orange);
        jButton40.setBackground(Color.orange);
        jButton41.setBackground(Color.orange);
        jButton42.setBackground(Color.orange);
        doituong.setBackground(Color.orange);
        doituong1.setBackground(Color.orange);
        doituong2.setBackground(Color.orange);
        doituong3.setBackground(Color.orange);
        doituong4.setBackground(Color.orange);
        doituong5.setBackground(Color.orange);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        tentaikhoanss = new javax.swing.JLabel();
        hotenss = new javax.swing.JLabel();
        diachiss = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        doituong = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        doituong1 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        doituong2 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        doituong3 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        doituong4 = new javax.swing.JButton();
        doituong5 = new javax.swing.JButton();
        anh = new javax.swing.JLabel();
        quyen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Quản lý bệnh viện");

        jButton21.setText("Đổi mật khẩu");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        tentaikhoanss.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tentaikhoanss.setForeground(new java.awt.Color(255, 51, 51));
        tentaikhoanss.setText("Tên tài khoản");

        hotenss.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hotenss.setForeground(new java.awt.Color(255, 51, 51));
        hotenss.setText("Xin chào: ");

        diachiss.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        diachiss.setForeground(new java.awt.Color(255, 51, 51));
        diachiss.setText("Địa chỉ");

        jButton22.setText("Bệnh nhân");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("Tài khoản");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("Gửi email");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setText("Nhóm máu");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setText("Thống kê");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("Loại sản phẩm");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText("Chức vụ");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        doituong.setBackground(new java.awt.Color(255, 51, 51));
        doituong.setText("Đối tượng");
        doituong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doituongActionPerformed(evt);
            }
        });

        jButton29.setText("Kho");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setText("Giường ngủ");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setText("Hóa đơn");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setText("Nhà tài trợ");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setText("Sản phẩm");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setText("Cuộc hẹn");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jButton35.setText("Tiền lương");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton36.setText("Loại giường");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.setText("Nhân viên");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton38.setText("Hóa đơn nhập");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.setText("Y tá");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        doituong1.setText("Bác sĩ");
        doituong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doituong1ActionPerformed(evt);
            }
        });

        jButton40.setText("Phản hồi");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        doituong2.setText("Thắc mắc");
        doituong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doituong2ActionPerformed(evt);
            }
        });

        jButton41.setText("Bệnh nhânđặc biệt");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        doituong3.setText("Bệnh nhân Covid-19");
        doituong3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doituong3ActionPerformed(evt);
            }
        });

        jButton42.setText("Bệnh hiếm gặp");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        doituong4.setText("Bệnh di chuyền");
        doituong4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doituong4ActionPerformed(evt);
            }
        });

        doituong5.setText("Chưa thanh toán");
        doituong5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doituong5ActionPerformed(evt);
            }
        });

        quyen.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doituong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton35, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tentaikhoanss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hotenss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(diachiss, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton30, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton36, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jButton34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton38, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jButton32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(doituong5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doituong1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doituong2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quyen, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doituong3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doituong4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton21)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(anh, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doituong2)
                        .addComponent(jButton40))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doituong1)
                        .addComponent(jButton39)
                        .addComponent(doituong5))
                    .addComponent(jButton21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doituong4)
                        .addComponent(jButton42))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(doituong3)
                        .addComponent(jButton41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(anh, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(quyen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tentaikhoanss, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hotenss, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diachiss, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doituong, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton33, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jButton31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(jButton25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(jButton22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
//        if(bv == null){
//            bv = new benhnhans();
//
//            tpan.addTab("Bệnh nhân", bv);
//        }
//
//        tpan.setSelectedComponent(bv);
          benhnhanss bn = new benhnhanss(this, true);
          bn.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("2") || phanquyen.equals("3")){
            jButton23.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
            // Khi người dùng click vào from khác thì sẽ hiển thị from đó lên
//            if(tk == null){ // Kiểm tra xem tab đó đã được mở chưa, nếu chưa được mở thì thực câu lệnh bên dưới
//                tk = new taikhoans(); // Khởi tạo from "studentManeger"
//                //ImageIcon icon = new ImageIcon(getClass().getResource("com/mycompany/testswing/icons/anh.jsp")); // Hiển thị icon trên thanh tab khi mở
//                //tpan.addTab("Quản lý sinh viên", icon, mStudent, "Quản lý sinh viên");
//                tpan.addTab("Quản lý đối tượng", tk); // Đặt tên cho tab đó
//            }
//            tpan.setSelectedComponent(tk); // Hiển thị tab đó lên
            // "tpan" nghĩa là tên của thẻ "panel" để hiển thị các tab lên đó, phải có thẻ "panel" thì mới hiển thị các tab lên được
            
            taikhoanss tk = new taikhoanss(this, true);
            tk.setVisible(true);
        }

    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton24.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(email == null){
//                email = new guiemail();
//
//                tpan.addTab("Gửi email", email);
//            }
//
//            tpan.setSelectedComponent(email);

             guiemails email = new guiemails(this, true);
             email.setVisible(true);
        }

    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        String phanuyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanuyen.equals("3")){
            jButton25.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
            // Khi người dùng click vào from khác thì sẽ hiển thị from đó lên
//            if(nm == null){ // Kiểm tra xem tab đó đã được mở chưa, nếu chưa được mở thì thực câu lệnh bên dưới
//                nm = new nhommaus(); // Khởi tạo from "studentManeger"
//                //ImageIcon icon = new ImageIcon(getClass().getResource("com/mycompany/testswing/icons/anh.jsp")); // Hiển thị icon trên thanh tab khi mở
//                //tpan.addTab("Quản lý sinh viên", icon, mStudent, "Quản lý sinh viên");
//                tpan.addTab("Quản lý đối tượng", nm); // Đặt tên cho tab đó
//            }
//            tpan.setSelectedComponent(nm); // Hiển thị tab đó lên
            // "tpan" nghĩa là tên của thẻ "panel" để hiển thị các tab lên đó, phải có thẻ "panel" thì mới hiển thị các tab lên được
            nhommauss nm = new nhommauss(this, true);
            nm.setVisible(true);
        }

    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
//        if(thongkes == null){
//            thongkes = new thongke();
//
//            tpan.addTab("Thống kê", thongkes);
//        }
//
//        tpan.setSelectedComponent(thongkes);

        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton26.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
            thongkes tk = new thongkes(this, true);
            tk.setVisible(true);
        }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton27.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
            // Khi người dùng click vào from khác thì sẽ hiển thị from đó lên
//            if(lsp == null){ // Kiểm tra xem tab đó đã được mở chưa, nếu chưa được mở thì thực câu lệnh bên dưới
//                lsp = new loaisanphams(); // Khởi tạo from "studentManeger"
//                //ImageIcon icon = new ImageIcon(getClass().getResource("com/mycompany/testswing/icons/anh.jsp")); // Hiển thị icon trên thanh tab khi mở
//                //tpan.addTab("Quản lý sinh viên", icon, mStudent, "Quản lý sinh viên");
//                tpan.addTab("Quản lý đối tượng", lsp); // Đặt tên cho tab đó
//            }
//            tpan.setSelectedComponent(lsp); // Hiển thị tab đó lên
            // "tpan" nghĩa là tên của thẻ "panel" để hiển thị các tab lên đó, phải có thẻ "panel" thì mới hiển thị các tab lên được
            loaigiuongss lsp = new loaigiuongss(this, true);
            lsp.setVisible(true);
        }

        //          test tests = new test(this, true);
        //          tests.setVisible(true);
        //          tests.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton27ActionPerformed
    
    private void phanquyens(){
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            doituong.hide();
            jButton22.hide();
            jButton38.hide();
            jButton37.hide();
            jButton36.hide();
            jButton35.hide();
            jButton34.hide();
            jButton32.hide();
            jButton30.hide();
            jButton29.hide();
            jButton28.hide();
            jButton27.hide();
            jButton23.hide();
            jButton24.hide();
            jButton25.hide();
            jButton26.hide();
            doituong5.hide();
            doituong1.hide();
            jButton39.hide();
            jButton40.hide();
            jButton41.hide();
            doituong3.hide();
            doituong4.hide();
            jButton42.hide();
            
        }
        if(phanquyen.equals("2")){
            jButton37.hide();
            jButton23.hide();
            jButton32.hide();
            jButton30.hide();
            jButton29.hide();
        }
    }
    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton28.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(cv == null){
//                cv = new chucvus();
//
//                tpan.addTab("Quản lý chức vụ", cv);
//            }
//            tpan.setSelectedComponent(cv);
              chucvuss cv = new chucvuss(this, true);
              cv.setVisible(true);
        }

    }//GEN-LAST:event_jButton28ActionPerformed

    private void doituongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doituongActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            doituong.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
            // Khi người dùng click vào from khác thì sẽ hiển thị from đó lên
//            if(doituongs == null){ // Kiểm tra xem tab đó đã được mở chưa, nếu chưa được mở thì thực câu lệnh bên dưới
//                doituongs = new doituongs(); // Khởi tạo from "studentManeger"
//                //ImageIcon icon = new ImageIcon(getClass().getResource("com/mycompany/testswing/icons/anh.jsp")); // Hiển thị icon trên thanh tab khi mở
//                //tpan.addTab("Quản lý sinh viên", icon, mStudent, "Quản lý sinh viên");
//                tpan.addTab("Quản lý đối tượng", doituongs); // Đặt tên cho tab đó
//            }
//            tpan.setSelectedComponent(doituongs); // Hiển thị tab đó lên
            // "tpan" nghĩa là tên của thẻ "panel" để hiển thị các tab lên đó, phải có thẻ "panel" thì mới hiển thị các tab lên được
            doiituongss dt = new doiituongss(this, true);
            dt.setVisible(true);
            
            
        }

    }//GEN-LAST:event_doituongActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton29.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(kh == null){
//                kh = new khos();
//
//                tpan.addTab("Kho", kh);
//            }
//
//            tpan.setSelectedComponent(kh);

              khoss kh = new khoss(this, true);
              kh.setVisible(true);
        }

    }//GEN-LAST:event_jButton29ActionPerformed
    
    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton30.hide();
           // MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(gn == null){
//                gn = new giuongngus();
//
//                tpan.addTab("Giường ngủ", gn);
//            }
//
//            tpan.setSelectedComponent(gn);

              giuongnguss gn = new giuongnguss(this, true);
              gn.setVisible(true);
        }

    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:

//        if(hd == null){
//            hd = new hoadons();
//
//            tpan.addTab("Hóa đơn", hd);
//        }
//
//        tpan.setSelectedComponent(hd);

          hoadonss hd = new hoadonss(this, true);
          hd.setVisible(true);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton32.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(ntt == null){
//                ntt = new nhataitros();
//
//                tpan.addTab("Nhà tài trợ", ntt);
//            }
//
//            tpan.setSelectedComponent(ntt);
              nhataitross ntt = new nhataitross(this, true);
              ntt.setVisible(true);
              
              jButton32.setBackground(Color.orange);
        }

    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
//        if(sp == null){
//            sp = new sanphams();
//
//            tpan.addTab("Sản phẩm", sp);
//        }
//
//        tpan.setSelectedComponent(sp);

          sanphamss sp = new sanphamss(this, true);
          sp.setVisible(true);
    }//GEN-LAST:event_jButton33ActionPerformed
    
    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton34.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(ch == null){
//                ch = new cuochens();
//
//                tpan.addTab("Cuộc hẹn", ch);
//            }
//
//            tpan.setSelectedComponent(ch);

              cuochenss ch = new cuochenss(this, true);
              ch.setVisible(true);
              jButton34.setBackground(Color.orange);
        }

    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3") || phanquyen.equals("2")){
            jButton35.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(tl == null){
//                tl = new tienluongs();
//
//                tpan.addTab("Tiền lương", tl);
//            }
//
//            tpan.setSelectedComponent(tl);

              tienluongss tl = new tienluongss(this, true);
              tl.setVisible(true);
              jButton35.setBackground(Color.orange);
        }

    }//GEN-LAST:event_jButton35ActionPerformed
    
    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        //        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton36.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(lg == null){
//                lg = new loaigiuongs();
//
//                tpan.addTab("Loại giường", lg);
//            }
//
//            tpan.setSelectedComponent(lg);

              loaigiuongss lg = new loaigiuongss(this, true);
              lg.setVisible(true);
              jButton36.setBackground(Color.orange);
        }

    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3") || phanquyen.equals("2")){
            jButton37.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(nv == null){
//                nv = new nhanviens();
//
//                tpan.addTab("Nhân viên", nv);
//            }
//
//            tpan.setSelectedComponent(nv);

             nhanvienss nv = new nhanvienss(this, true);
             nv.setVisible(true);
             jButton37.setBackground(Color.orange);
        }

    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        if(phanquyen.equals("3")){
            jButton38.hide();
            //MessageDialog.showMessageError(this, "Bạn không có quyền", "Lỗi");
        }else{
//            if(hdn == null){
//                hdn = new hoadonnhaps();
//
//                tpan.addTab("Hóa đơn nhập", hdn);
//            }
//
//            tpan.setSelectedComponent(hdn);
              hoadonnhapss hdn = new hoadonnhapss(this, true);
              hdn.setVisible(true);
              jButton38.setBackground(Color.orange);
        }

    }//GEN-LAST:event_jButton38ActionPerformed
    
    private void checkLogin(){
        int phanquyen = ShereData.dangnhapss.getPhanquyen();
        if(phanquyen == 1){
            quyen.setForeground(Color.red);
            quyen.setText("Admin");
        }
        if(phanquyen == 2){
            quyen.setForeground(Color.red);
            quyen.setText("Quản lý");
        }
        if(phanquyen == 3){
            quyen.setForeground(Color.red);
            quyen.setText("Bệnh nhân");
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        logins lg = new logins(this, true);
        lg.setVisible(true);
        phanquyen();
        phanquyens();
        shows();
        checkLogin();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/btljava/icon/Picture3.png")); // Khi người dùng chưa nhập hình ảnh vào thì hệ thống sẽ hiển thị hình ảnh mặc định
                                                                    // "getResource()" Nghĩa là đường dẫn đến hình ảnh
        anh.setIcon(icon);
        
        
        
//        phanquyens();
    }//GEN-LAST:event_formWindowOpened

    private void shows(){
        int phanquyens = 0;
        String hoten = "";
        String diachi = "";
        String phanquyen = String.valueOf(ShereData.dangnhapss.getPhanquyen());
        phanquyens = Integer.parseInt(phanquyen);
        String taikhoan = String.valueOf(ShereData.dangnhapss.getTentaikhoan());
        if(phanquyens == 3){
            hoten = String.valueOf(ShereData.dangnhapss.getHoten());
            diachi = String.valueOf(ShereData.dangnhapss.getDiachi());
        }else{
            hoten = String.valueOf(ShereData.dangnhapss.getHotens());
            diachi = String.valueOf(ShereData.dangnhapss.getDiachis());
        }
        
        tentaikhoanss.setText("Tên tài khoản:    " + taikhoan);
        hotenss.setText("Xin chào:      "+ hoten);
        diachiss.setText("Địa chỉ:      " + diachi);
        
        
    }
    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        doimatkhau dmk = new doimatkhau(this, true);
        dmk.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        // TODO add your handling code here:
        ytas yt = new ytas(this, true);
        yt.setVisible(true);
    }//GEN-LAST:event_jButton39ActionPerformed

    private void doituong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doituong1ActionPerformed
        // TODO add your handling code here:
        bacsis bs = new bacsis(this, true);
        bs.setVisible(true);
    }//GEN-LAST:event_doituong1ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        // TODO add your handling code here:
        
        phanhois ph = new phanhois(this, true);
        ph.setVisible(true);
    }//GEN-LAST:event_jButton40ActionPerformed

    private void doituong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doituong2ActionPerformed
        // TODO add your handling code here:
        thacmacs tm = new thacmacs(this, true);
        tm.setVisible(true);
    }//GEN-LAST:event_doituong2ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        // TODO add your handling code here:
        benhnhandacbiet db = new benhnhandacbiet(this, true);
        db.setVisible(true);
    }//GEN-LAST:event_jButton41ActionPerformed

    private void doituong3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doituong3ActionPerformed
        // TODO add your handling code here:
        benhnhancovid cv = new benhnhancovid(this, true);
        cv.setVisible(true);
    }//GEN-LAST:event_doituong3ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        // TODO add your handling code here:
        benhhiemgap hg = new benhhiemgap(this, true);
        hg.setVisible(true);
    }//GEN-LAST:event_jButton42ActionPerformed

    private void doituong4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doituong4ActionPerformed
        // TODO add your handling code here:
        benhdichuyen dc = new benhdichuyen(this, true);
        dc.setVisible(true);
    }//GEN-LAST:event_doituong4ActionPerformed

    private void doituong5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doituong5ActionPerformed
        // TODO add your handling code here:
        chuathanhtoantien t = new chuathanhtoantien(this, true);
        t.setVisible(true);
    }//GEN-LAST:event_doituong5ActionPerformed
    
    private void phanquyen(){
        String tentaikhoans = String.valueOf(ShereData.dangnhap.getTentaikhoan());
        String phanquyen = String.valueOf(ShereData.dangnhap.getPhanquyen());
        //taikhoans.setText("Xin chào " + tentaikhoan);
        if(phanquyen.equals("1")){
            //doituong.hide();
            
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromMainss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromMainss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromMainss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromMainss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromMainss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anh;
    private javax.swing.JLabel diachiss;
    private javax.swing.JButton doituong;
    private javax.swing.JButton doituong1;
    private javax.swing.JButton doituong2;
    private javax.swing.JButton doituong3;
    private javax.swing.JButton doituong4;
    private javax.swing.JButton doituong5;
    private javax.swing.JLabel hotenss;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton quyen;
    private javax.swing.JLabel tentaikhoanss;
    // End of variables declaration//GEN-END:variables
}
